//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generator name    : pulse_ast
//     Generator version : 1.0.0-alpha
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pulse.CodeAnalysis.FrontEnd
{
    public interface IStatementVisitor
    {
        void VisitExpressionStatement(ExpressionStatement statement);
        void VisitPrintStatement(PrintStatement statement);
    }
    public abstract class Statement
    {
        public abstract void Accept(IStatementVisitor visitor);
    }
    public sealed class ExpressionStatement : Statement
    {
        public Expression Expression { get; }
        
        public ExpressionStatement(Expression expression)
        {
            Expression = expression;
        }
        
        public override void Accept(IStatementVisitor visitor)
            => visitor.VisitExpressionStatement(this);
    }
    public sealed class PrintStatement : Statement
    {
        public Expression Expression { get; }
        
        public PrintStatement(Expression expression)
        {
            Expression = expression;
        }
        
        public override void Accept(IStatementVisitor visitor)
            => visitor.VisitPrintStatement(this);
    }
}
